### ISSUE TITLE
Missing Refactorings inside of Anonymous Class

### ISSUE THREAD

**Issue by mkshiblu** [tsantalis/RefactoringMiner#162] opened 2021-02-18 22:30 UTC
#### Steps to Reproduce

1. Go to -
  https://github.com/mkshiblu/practice/commit/443d07d186187d49efb63f86f2c9750e0f1af993
2.  Run the chrome extension 

#### Observed Behavior
The extension reported that "No Refactorings Found**

#### Expected Behavior
The extension should have reported that the following refactorings 

1. Change Return Type Address[] to List<Address> in method createAddresses(count int) : List<Address>
2. Extract Method createAddress(host String, port int) : Address extracted from createAddresses(count int) : Address[]
3. Change Variable Type addresses : Address[] to addresses : List<Address> in method createAddresses(count int) : List<Address>

Note that the expected behavior comes from the observation when the anonymous class is extracted into a normal class declaration.

It seems Extract Method refactorings are not reported from inside of anonymous classes. 

#### Snippet Diff

![image](https://user-images.githubusercontent.com/15908043/108430052-c9761600-720e-11eb-956d-3c25338bc73f.png)

**Refactoring Miner Version**
**Commit:** ff4cfbe
**Commit Date:**  February 18, 2021

**Comment by tsantalis** [comment] 2021-02-19 05:01
duplicate of issue #119

**Comment by tsantalis** [comment] 2021-03-07 13:37
In the oracle one case of Extract Method was found inside anonymous class in commit
https://github.com/VoltDB/voltdb/commit/669e0722324965e3c99f29685517ac24d4ff2848
`Extract Method private writeResponseToConnection(response ClientResponseImpl) : void extracted from public run() : void in class org.voltdb.ClientInterface.processFinishedCompilerWork.ft.create`

**Closed** 2021-03-07 13:40 UTC
