### ISSUE TITLE
Replacement inaccuracy within an Extract Method refactoring

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#348] opened 2023-02-01 01:19 UTC
**Problem**

Replacements reporteds by RefactoringMiner for two statement mapping are inaccurate within two similar Extract Methods

**Commit**

[Here](https://github.com/neo4j/neo4j/commit/b83e6a535cbca21d5ea764b0c49bfca8a9ff9db4)

**File**

[LuceneIndexAccessorReader.java](https://github.com/neo4j/neo4j/commit/b83e6a535cbca21d5ea764b0c49bfca8a9ff9db4#diff-20a7f1613626b9b71f3c54d9e85d9ab21c4ca718357f827ca5de41fa51e5353b)

**Refactoring operations**

1- Extract Method **protected query(query Query)** : PrimitiveLongIterator extracted **from public lookup(value Object)** : PrimitiveLongIterator in class org.neo4j.kernel.api.impl.index.LuceneIndexAccessorReader

2- Extract Method **protected query(query Query)** : PrimitiveLongIterator extracted **from public scan()** : PrimitiveLongIterator in class org.neo4j.kernel.api.impl.index.LuceneIndexAccessorReader

**Problem description**

In the first Extract Method case, in the following statement mapping:

- `Hits hits=new Hits(searcher,documentLogic.newQuery(value),null);`

To

- `Hits hits=new Hits(searcher,query,null);`

The reported replacement after the argumentization is **"documentLogic.newQuery(value) -> documentLogic.newValueQuery(value)"** with the type of VariableReplacementWithMethodInvocation, which is not accurate. Instead, if RefactoringMiner can report a replacement like: **"newQuery(value)"** -> **"newValueQuery(value)"** with the type of MethodInvocationReplacement, it would be ideal. Since there is a Rename Method refactoring within this commit, PurityChecker would be able to justify this change if it has access to the correct replacement.

Same happened for the other Extract Method refactoring. The ideal replacement in this case would be **"newMatchAllQuery()"** -> **"newAllQuery()"**, with the same type mentioned above.

**Comment by tsantalis** [comment] 2023-02-09 08:17
![Screenshot from 2023-02-09 03-15-56](https://user-images.githubusercontent.com/1483516/217755410-5bd4f68c-a0d5-4840-91d6-e7ded69c12bf.png)

**Comment by tsantalis** [comment] 2023-02-09 08:28
@pedramnoori 

The reason the replacement is of type `VariableReplacementWithMethodInvocation`
is because the actual replacement is done with the parameter `query` in the extracted method.
It is not possible to change the type of the replacement.

Please use new API `ExtractOperationRefactoring.getArgumentMappings()` to get sub-expression (AbstractCall) mappings
"newQuery(value)" -> "newValueQuery(value)"
"newMatchAllQuery()" -> "newAllQuery()"
and infer the method invocation rename on your side.

**Comment by tsantalis** [comment] 2023-02-16 00:49
@pouryafard75 
I am closing the issue. I suppose your are working on improving the diff of the argument mappings.

**Closed by tsantalis** 2023-02-16 00:49 UTC

**Comment by pouryafard75** [comment] 2023-02-16 00:52
@tsantalis Yes, the problem is solved on my end. 
It will be available in my upcoming PR.
