### ISSUE TITLE
Timeout Exception opentripplanner/OpenTripPlanner 474c851

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#627] opened 2024-01-28 04:25 UTC
https://github.com/opentripplanner/OpenTripPlanner/commit/474c8513ec83262b8862026e0a13cf2baf51bdbd timed out
```
92136696 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 474c8513ec83262b8862026e0a13cf2baf51bdbd
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment] 2024-02-02 17:57
Duplicate of issue #622 #623

Refactorings at 474c8513ec83262b8862026e0a13cf2baf51bdbd
Rename Parameter	index : RoutingService to routingService : RoutingService in method public SiriFuzzyTripMatcher(routingService RoutingService) from class org.opentripplanner.ext.siri.SiriFuzzyTripMatcher
Add Parameter	routingService : RoutingService in method public getMonoOrMultiModalStation(idString String, routingService RoutingService) : MonoOrMultiModalStation from class org.opentripplanner.ext.transmodelapi.mapping.TransmodelMappingUtil
Remove Parameter	stationById : Map<FeedScopedId,Station> in method public getMonoOrMultiModalStation(idString String, stationById Map<FeedScopedId,Station>, multiModalStationById Map<FeedScopedId,MultiModalStation>, multimodalStationForStations Map<Station,MultiModalStation>) : MonoOrMultiModalStation from class org.opentripplanner.ext.transmodelapi.mapping.TransmodelMappingUtil
Remove Parameter	multiModalStationById : Map<FeedScopedId,MultiModalStation> in method public getMonoOrMultiModalStation(idString String, stationById Map<FeedScopedId,Station>, multiModalStationById Map<FeedScopedId,MultiModalStation>, multimodalStationForStations Map<Station,MultiModalStation>) : MonoOrMultiModalStation from class org.opentripplanner.ext.transmodelapi.mapping.TransmodelMappingUtil
Remove Parameter	multimodalStationForStations : Map<Station,MultiModalStation> in method public getMonoOrMultiModalStation(idString String, stationById Map<FeedScopedId,Station>, multiModalStationById Map<FeedScopedId,MultiModalStation>, multimodalStationForStations Map<Station,MultiModalStation>) : MonoOrMultiModalStation from class org.opentripplanner.ext.transmodelapi.mapping.TransmodelMappingUtil
Rename Parameter	index : RoutingService to routingService : RoutingService in method public TripTimeShortHelper(routingService RoutingService) from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Rename Attribute	index : RoutingService to routingService : RoutingService in class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Change Attribute Access Modifier	public to private in attribute private graph : Graph from class org.opentripplanner.routing.RoutingService
Change Attribute Access Modifier	public to private in attribute private graphQL : GraphQL from class org.opentripplanner.routing.RoutingService
Encapsulate Attribute	private graphQL : GraphQL from class org.opentripplanner.routing.RoutingService
Replace Attribute With Variable	calendarService : CalendarService to calendarService : CalendarService in method private initalizeServiceCodesForDate(graph Graph) : void from class org.opentripplanner.routing.graph.GraphIndex
Move Method	public getTripTimesShort(trip Trip, serviceDate ServiceDate) : List<TripTimeShort> from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper to public getTripTimesShort(trip Trip, serviceDate ServiceDate) : List<TripTimeShort> from class org.opentripplanner.routing.RoutingService
Extract And Move Method	public getServicesRunningForDate(date ServiceDate) : BitSet extracted from public getTrip(route Route, direction int, startTime int, date ServiceDate) : Trip in class org.opentripplanner.updater.GtfsRealtimeFuzzyTripMatcher & moved to class org.opentripplanner.routing.RoutingService
Extract And Move Method	public getTripPatternForId(id String) : TripPattern extracted from public getPattern(patternIdString String) : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Remove Parameter Annotation	@PathParam("patternId") in parameter patternIdString : String in method public getPattern(patternIdString String) : Response from class org.opentripplanner.index.IndexAPI
Rename Parameter	patternIdString : String to id : String in method public getTripPatternForId(id String) : TripPattern from class org.opentripplanner.routing.RoutingService
Rename Parameter	patternIdString : String to id : String in method public getTripPatternForId(id String) : TripPattern from class org.opentripplanner.routing.RoutingService
Rename Parameter	patternIdString : String to id : String in method public getTripPatternForId(id String) : TripPattern from class org.opentripplanner.routing.RoutingService
Rename Parameter	patternIdString : String to id : String in method public getTripPatternForId(id String) : TripPattern from class org.opentripplanner.routing.RoutingService
Rename Parameter	patternIdString : String to id : String in method public getTripPatternForId(id String) : TripPattern from class org.opentripplanner.routing.RoutingService
Extract And Move Method	public getTripPatternForId(id String) : TripPattern extracted from public getTripsForPattern(patternIdString String) : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Remove Parameter Annotation	@PathParam("patternId") in parameter patternIdString : String in method public getTripsForPattern(patternIdString String) : Response from class org.opentripplanner.index.IndexAPI
Extract And Move Method	public getTripPatternForId(id String) : TripPattern extracted from public getStopsForPattern(patternIdString String) : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Remove Parameter Annotation	@PathParam("patternId") in parameter patternIdString : String in method public getStopsForPattern(patternIdString String) : Response from class org.opentripplanner.index.IndexAPI
Extract And Move Method	public getTripPatternForId(id String) : TripPattern extracted from public getSemanticHashForPattern(patternIdString String) : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Remove Parameter Annotation	@PathParam("patternId") in parameter patternIdString : String in method public getSemanticHashForPattern(patternIdString String) : Response from class org.opentripplanner.index.IndexAPI
Extract And Move Method	public getTripPatternForId(id String) : TripPattern extracted from public getGeometryForPattern(patternIdString String) : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Remove Parameter Annotation	@PathParam("patternId") in parameter patternIdString : String in method public getGeometryForPattern(patternIdString String) : Response from class org.opentripplanner.index.IndexAPI
Extract And Move Method	public getTripPatterns() : Collection<TripPattern> extracted from public getPatterns() : Response in class org.opentripplanner.index.IndexAPI & moved to class org.opentripplanner.routing.RoutingService
Extract And Move Method	public getStationById(id FeedScopedId) : Station extracted from public getMonoOrMultiModalStation(idString String, stationById Map<FeedScopedId,Station>, multiModalStationById Map<FeedScopedId,MultiModalStation>, multimodalStationForStations Map<Station,MultiModalStation>) : MonoOrMultiModalStation in class org.opentripplanner.ext.transmodelapi.mapping.TransmodelMappingUtil & moved to class org.opentripplanner.routing.RoutingService

**Closed by tsantalis** 2024-02-02 17:57 UTC
