### ISSUE TITLE
Clone the git repository error

### ISSUE THREAD

**Issue by rdurelli** [tsantalis/RefactoringMiner#257] opened 2022-06-15 10:57 UTC
I just cloned the repo, when trying to execute it on my machine i got the following message:

`Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find any matches for org.osgi.service:org.osgi.service.prefs:[1.1.0,1.2.0) as no versions of org.osgi.service:org.osgi.service.prefs are available.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/osgi/service/org.osgi.service.prefs/maven-metadata.xml
     Required by:
         project : > org.eclipse.jdt:org.eclipse.jdt.core:3.27.0 > org.eclipse.platform:org.eclipse.core.runtime:3.25.0 > org.eclipse.platform:org.eclipse.equinox.preferences:3.10.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`

How to solve this? Thanks in advance.

**Comment by tsantalis** [comment] 2022-06-17 10:03
Please update to the latest commit and build again.
The issue is resolved in commit
https://github.com/tsantalis/RefactoringMiner/commit/f0a40425baed0ac7b9560e2a090f3f8925207619

**Closed by tsantalis** 2022-06-17 10:03 UTC
