### ISSUE TITLE
NPE Lombok 415e303a

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#573] opened 2024-01-25 20:45 UTC
NPE thrown while analyzing https://github.com/projectlombok/lombok/commit/415e303ac283df8d694b311f4f8df08f6e79cf0e
```
101802058 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 415e303ac283df8d694b311f4f8df08f6e79cf0e
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getNonMappedLeavesT2()" because "candidateMapper" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getNonMappedLeavesT2()" because "candidateMapper" is null
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.inferAttributeMergesAndSplits(UMLAbstractClassDiff.java:1062)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:664)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2121)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:163)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detect$3(GitHistoryRefactoringMinerImpl.java:760)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsantalis** [comment] 2024-01-25 21:53
@victorgveloso 
Duplicate of #572

Refactorings at 415e303ac283df8d694b311f4f8df08f6e79cf0e
Rename Method	public constructorExists(node EclipseNode, parameters List<SuperParameter>) : MemberExistsResult renamed to public hasConstructor(node EclipseNode, paramTypes Class<?>...) : MemberExistsResult in class lombok.eclipse.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode EclipseNode, level AccessLevel, parameters List<SuperParameter>, skipIfConstructorExists boolean, sourceNode EclipseNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast Annotation, annotationNode EclipseNode) : void in class lombok.eclipse.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode EclipseNode, level AccessLevel, parameters List<SuperParameter>, skipIfConstructorExists boolean, sourceNode EclipseNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast Annotation, annotationNode EclipseNode) : void in class lombok.eclipse.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode EclipseNode, level AccessLevel, parameters List<SuperParameter>, skipIfConstructorExists boolean, sourceNode EclipseNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast Annotation, annotationNode EclipseNode) : void in class lombok.eclipse.handlers.HandleStandardException
Extract Method	private generateNoArgsConstructor(typeNode EclipseNode, level AccessLevel, source EclipseNode) : void extracted from public handle(annotation AnnotationValues<StandardException>, ast Annotation, annotationNode EclipseNode) : void in class lombok.eclipse.handlers.HandleStandardException
Remove Parameter	parameters : List<SuperParameter> in method public constructorExists(node EclipseNode, parameters List<SuperParameter>) : MemberExistsResult from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	paramTypes : Class<?>... in method public hasConstructor(node EclipseNode, paramTypes Class<?>...) : MemberExistsResult from class lombok.eclipse.handlers.HandleStandardException
Split Conditional	fieldNames.expressions[ctr]=new StringLiteral(fieldName,pS,pE,0); to [fieldNames.expressions=new Expression[(msgParam && causeParam) ? 2 : 1];, if(causeParam)] in method public createConstructorProperties(source ASTNode, msgParam boolean, causeParam boolean) : Annotation[] from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	msgParam : boolean in method public createConstructorProperties(source ASTNode, msgParam boolean, causeParam boolean) : Annotation[] from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	causeParam : boolean in method public createConstructorProperties(source ASTNode, msgParam boolean, causeParam boolean) : Annotation[] from class lombok.eclipse.handlers.HandleStandardException
Remove Parameter	fields : Collection<SuperParameter> in method public createConstructorProperties(source ASTNode, fields Collection<SuperParameter>) : Annotation[] from class lombok.eclipse.handlers.HandleStandardException
Extract Variable	pS : int in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Rename Parameter	type : EclipseNode to typeNode : EclipseNode in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Rename Variable	fieldPos : long to p : long in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	msgParam : boolean in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	causeParam : boolean in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	explicitCall : ExplicitConstructorCall in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Add Parameter	extra : Statement in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Remove Parameter	parameters : Collection<SuperParameter> in method public createConstructor(level AccessLevel, type EclipseNode, parameters Collection<SuperParameter>, sourceNode EclipseNode) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Replace Variable With Attribute	fieldName : char[] to MESSAGE : char[] in method public createConstructor(level AccessLevel, typeNode EclipseNode, msgParam boolean, causeParam boolean, sourceNode EclipseNode, explicitCall ExplicitConstructorCall, extra Statement) : ConstructorDeclaration from class lombok.eclipse.handlers.HandleStandardException
Rename Method	public constructorExists(node JavacNode, parameters List<SuperParameter>) : MemberExistsResult renamed to private hasConstructor(node JavacNode, paramTypes Class<?>...) : MemberExistsResult in class lombok.javac.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode JavacNode, level AccessLevel, fields List<SuperParameter>, skipIfConstructorExists boolean, source JavacNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast JCAnnotation, annotationNode JavacNode) : void in class lombok.javac.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode JavacNode, level AccessLevel, fields List<SuperParameter>, skipIfConstructorExists boolean, source JavacNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast JCAnnotation, annotationNode JavacNode) : void in class lombok.javac.handlers.HandleStandardException
Inline Method	public generateConstructor(typeNode JavacNode, level AccessLevel, fields List<SuperParameter>, skipIfConstructorExists boolean, source JavacNode) : void inlined to public handle(annotation AnnotationValues<StandardException>, ast JCAnnotation, annotationNode JavacNode) : void in class lombok.javac.handlers.HandleStandardException
Extract Variable	access : AccessLevel in method public handle(annotation AnnotationValues<StandardException>, ast JCAnnotation, annotationNode JavacNode) : void from class lombok.javac.handlers.HandleStandardException
Extract Method	private generateNoArgsConstructor(typeNode JavacNode, level AccessLevel, source JavacNode) : void extracted from public handle(annotation AnnotationValues<StandardException>, ast JCAnnotation, annotationNode JavacNode) : void in class lombok.javac.handlers.HandleStandardException
Rename Parameter	parameters : List<SuperParameter> to paramTypes : Class<?>... in method private hasConstructor(node JavacNode, paramTypes Class<?>...) : MemberExistsResult from class lombok.javac.handlers.HandleStandardException
Change Parameter Type	parameters : List<SuperParameter> to paramTypes : Class<?>... in method private hasConstructor(node JavacNode, paramTypes Class<?>...) : MemberExistsResult from class lombok.javac.handlers.HandleStandardException
Change Method Access Modifier	public to private in method private hasConstructor(node JavacNode, paramTypes Class<?>...) : MemberExistsResult from class lombok.javac.handlers.HandleStandardException
Add Parameter	msgParam : boolean in method private addConstructorProperties(mods JCModifiers, node JavacNode, msgParam boolean, causeParam boolean) : void from class lombok.javac.handlers.HandleStandardException
Add Parameter	causeParam : boolean in method private addConstructorProperties(mods JCModifiers, node JavacNode, msgParam boolean, causeParam boolean) : void from class lombok.javac.handlers.HandleStandardException
Remove Parameter	fields : List<SuperParameter> in method public addConstructorProperties(mods JCModifiers, node JavacNode, fields List<SuperParameter>) : void from class lombok.javac.handlers.HandleStandardException
Change Method Access Modifier	public to private in method private addConstructorProperties(mods JCModifiers, node JavacNode, msgParam boolean, causeParam boolean) : void from class lombok.javac.handlers.HandleStandardException
Parameterize Variable	statements : ListBuffer<JCStatement> to statements : List<JCStatement> in method private createConstructor(level AccessLevel, typeNode JavacNode, msgParam boolean, causeParam boolean, source JavacNode, statements List<JCStatement>) : JCMethodDecl from class lombok.javac.handlers.HandleStandardException
Change Variable Type	statements : ListBuffer<JCStatement> to statements : List<JCStatement> in method private createConstructor(level AccessLevel, typeNode JavacNode, msgParam boolean, causeParam boolean, source JavacNode, statements List<JCStatement>) : JCMethodDecl from class lombok.javac.handlers.HandleStandardException
Split Parameter	fieldsToParam : List<SuperParameter> to [causeParam : boolean, msgParam : boolean] in method private createConstructor(level AccessLevel, typeNode JavacNode, msgParam boolean, causeParam boolean, source JavacNode, statements List<JCStatement>) : JCMethodDecl from class lombok.javac.handlers.HandleStandardException
Change Method Access Modifier	public to private in method private createConstructor(level AccessLevel, typeNode JavacNode, msgParam boolean, causeParam boolean, source JavacNode, statements List<JCStatement>) : JCMethodDecl from class lombok.javac.handlers.HandleStandardException
Change Parameter Type	message : String to message : java.lang.String in method public EmptyException(message java.lang.String) from class EmptyException
Change Parameter Type	cause : Throwable to cause : java.lang.Throwable in method public EmptyException(cause java.lang.Throwable) from class EmptyException
Change Parameter Type	message : String to message : java.lang.String in method public EmptyException(message java.lang.String, cause java.lang.Throwable) from class EmptyException
Change Parameter Type	cause : Throwable to cause : java.lang.Throwable in method public EmptyException(message java.lang.String, cause java.lang.Throwable) from class EmptyException
Change Parameter Type	message : String to message : java.lang.String in method protected NoArgsException(message java.lang.String) from class NoArgsException
Change Method Access Modifier	public to protected in method protected NoArgsException(message String) from class NoArgsException
Change Parameter Type	cause : Throwable to cause : java.lang.Throwable in method protected NoArgsException(cause java.lang.Throwable) from class NoArgsException
Change Method Access Modifier	public to protected in method protected NoArgsException(cause Throwable) from class NoArgsException
Change Parameter Type	message : String to message : java.lang.String in method protected NoArgsException(message java.lang.String, cause java.lang.Throwable) from class NoArgsException
Change Parameter Type	cause : Throwable to cause : java.lang.Throwable in method protected NoArgsException(message java.lang.String, cause java.lang.Throwable) from class NoArgsException
Change Method Access Modifier	public to protected in method protected NoArgsException(message String, cause Throwable) from class NoArgsException
Modify Class Annotation	@StandardException to @StandardException(access = AccessLevel.PROTECTED) in class NoArgsException
Rename Parameter	params : List<JCVariableDecl> to a : List<JCVariableDecl> in method private paramsMatch(node JavacNode, a List<JCVariableDecl>, b Class<?>[]) : boolean from class lombok.javac.handlers.HandleStandardException

**Closed by tsantalis** 2024-01-25 21:53 UTC
