### ISSUE TITLE
NPE TIBCOSoftware/jasperreports da2b807d

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#582] opened 2024-01-25 21:31 UTC
NPE thrown while analyzing https://github.com/TIBCOSoftware/jasperreports/commit/da2b807d3d0a6250dd66da8d042162d9838fe36a
```
88206751 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit da2b807d3d0a6250dd66da8d042162d9838fe36a
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getNonMappedLeavesT1()" because "candidateMapper" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.NullPointerException: Cannot invoke "gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getNonMappedLeavesT1()" because "candidateMapper" is null
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.inferAttributeMergesAndSplits(UMLAbstractClassDiff.java:1016)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.getRefactorings(UMLAbstractClassDiff.java:664)
	at gr.uom.java.xmi.diff.UMLModelDiff.getRefactorings(UMLModelDiff.java:2121)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:163)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detect$3(GitHistoryRefactoringMinerImpl.java:760)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsantalis** [comment] 2024-01-26 16:57
@victorgveloso 
Duplicate of #572
Fixed in https://github.com/tsantalis/RefactoringMiner/commit/e4d9030faa41a4255114879fcecf6eeed84f412d

Refactorings at da2b807d3d0a6250dd66da8d042162d9838fe36a
Merge Parameter	[locale : Locale, resBundle : ResourceBundle] to isXML : boolean in method public JRDesignViewer(fileName String, isXML boolean) from class net.sf.jasperreports.view.JRDesignViewer
Rename Parameter	isXmlFile : boolean to isXML : boolean in method public JRDesignViewer(fileName String, isXML boolean) from class net.sf.jasperreports.view.JRDesignViewer
Remove Parameter	jrPrint : JasperPrint in method public JRDesignViewer(fileName String, jrPrint JasperPrint, isXmlFile boolean, locale Locale, resBundle ResourceBundle) from class net.sf.jasperreports.view.JRDesignViewer
Change Attribute Access Modifier	private to protected in attribute protected zoom : float from class net.sf.jasperreports.view.JRViewer
Rename Method	public viewReport(sourceFile String, isXMLFile boolean) : void renamed to public viewReportDesign(sourceFile String, isXML boolean) : void in class net.sf.jasperreports.view.JasperDesignViewer
Rename Method	public viewReport(is InputStream, isXMLFile boolean, isExitOnClose boolean, locale Locale) : void renamed to public viewReportDesign(is InputStream, isXML boolean) : void in class net.sf.jasperreports.view.JasperDesignViewer
Rename Method	public viewReport(jasperPrint JasperPrint) : void renamed to public viewReportDesign(report JRReport) : void in class net.sf.jasperreports.view.JasperDesignViewer
Inline Method	public JasperDesignViewer(is InputStream, isXMLFile boolean, isExitOnClose boolean, locale Locale) inlined to public JasperDesignViewer(report JRReport) in class net.sf.jasperreports.view.JasperDesignViewer
Inline Method	public viewReport(sourceFile String, isXMLFile boolean, isExitOnClose boolean, locale Locale) : void inlined to public viewReportDesign(sourceFile String, isXML boolean) : void in class net.sf.jasperreports.view.JasperDesignViewer
Inline Method	public viewReport(jasperPrint JasperPrint, isExitOnClose boolean, locale Locale) : void inlined to public viewReportDesign(report JRReport) : void in class net.sf.jasperreports.view.JasperDesignViewer
Replace Attribute With Variable	viewer : JRDesignViewer to viewer : JRDesignViewer in method public JasperDesignViewer(report JRReport) from class net.sf.jasperreports.view.JasperDesignViewer
Rename Variable	jasperViewer : JasperDesignViewer to jasperDesignViewer : JasperDesignViewer in method public viewReportDesign(sourceFile String, isXML boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer
Rename Variable	jasperViewer : JasperDesignViewer to jasperDesignViewer : JasperDesignViewer in method public viewReportDesign(report JRReport) : void from class net.sf.jasperreports.view.JasperDesignViewer
Replace Attribute With Variable	viewer : JRDesignViewer to viewer : JRDesignViewer in method public JasperDesignViewer(sourceFile String, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Merge Parameter	[jrPrint : JasperPrint, locale : Locale] to isXML : boolean in method public JasperDesignViewer(sourceFile String, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Rename Parameter	isExitOnClose : boolean to isXML : boolean in method public JasperDesignViewer(sourceFile String, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Add Parameter	sourceFile : String in method public JasperDesignViewer(sourceFile String, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Rename Parameter	isXMLFile : boolean to isXML : boolean in method public JasperDesignViewer(is InputStream, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Add Parameter	is : InputStream in method public JasperDesignViewer(is InputStream, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Remove Parameter	sourceFile : String in method public JasperDesignViewer(sourceFile String, isXMLFile boolean, isExitOnClose boolean, locale Locale) from class net.sf.jasperreports.view.JasperDesignViewer
Remove Parameter	isExitOnClose : boolean in method public JasperDesignViewer(sourceFile String, isXMLFile boolean, isExitOnClose boolean, locale Locale) from class net.sf.jasperreports.view.JasperDesignViewer
Remove Parameter	locale : Locale in method public JasperDesignViewer(sourceFile String, isXMLFile boolean, isExitOnClose boolean, locale Locale) from class net.sf.jasperreports.view.JasperDesignViewer
Rename Parameter	isXMLFile : boolean to isXML : boolean in method public viewReportDesign(sourceFile String, isXML boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer
Rename Variable	jasperViewer : JasperDesignViewer to jasperDesignViewer : JasperDesignViewer in method public viewReportDesign(is InputStream, isXML boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer
Rename Parameter	isXMLFile : boolean to isXML : boolean in method public viewReportDesign(is InputStream, isXML boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer
Remove Parameter	isExitOnClose : boolean in method public viewReport(is InputStream, isXMLFile boolean, isExitOnClose boolean, locale Locale) : void from class net.sf.jasperreports.view.JasperDesignViewer
Remove Parameter	locale : Locale in method public viewReport(is InputStream, isXMLFile boolean, isExitOnClose boolean, locale Locale) : void from class net.sf.jasperreports.view.JasperDesignViewer
Rename Parameter	jasperPrint : JasperPrint to report : JRReport in method public viewReportDesign(report JRReport) : void from class net.sf.jasperreports.view.JasperDesignViewer
Change Parameter Type	jasperPrint : JasperPrint to report : JRReport in method public viewReportDesign(report JRReport) : void from class net.sf.jasperreports.view.JasperDesignViewer
Parameterize Attribute	reportFileName : String to sourceFile : String in method public JasperDesignViewer(sourceFile String, isXML boolean) from class net.sf.jasperreports.view.JasperDesignViewer
Move Method	private verifyDesign(jasperDesign JasperDesign) : void from class net.sf.jasperreports.view.JasperDesignViewer to private verifyDesign(jasperDesign JasperDesign) : void from class net.sf.jasperreports.view.JRDesignViewer
Change Method Access Modifier	private to protected in method protected loadReport(fileName String, isXmlReport boolean) : void from class net.sf.jasperreports.view.JRDesignViewer
Move Method	private loadReport(fileName String, isXmlReport boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer to protected loadReport(fileName String, isXmlReport boolean) : void from class net.sf.jasperreports.view.JRDesignViewer
Change Method Access Modifier	private to protected in method protected loadReport(is InputStream, isXmlReport boolean) : void from class net.sf.jasperreports.view.JRDesignViewer
Move Method	private loadReport(is InputStream, isXmlReport boolean) : void from class net.sf.jasperreports.view.JasperDesignViewer to protected loadReport(is InputStream, isXmlReport boolean) : void from class net.sf.jasperreports.view.JRDesignViewer
Remove Parameter	fileName : String in method private setReport(report JRReport, fileName String) : void from class net.sf.jasperreports.view.JasperDesignViewer
Move Method	private setReport(report JRReport, fileName String) : void from class net.sf.jasperreports.view.JasperDesignViewer to private setReport(report JRReport) : void from class net.sf.jasperreports.view.JRDesignViewer
Move Attribute	private reportFileName : String from class net.sf.jasperreports.view.JasperDesignViewer to private reportFileName : String from class net.sf.jasperreports.view.JRDesignViewer

**Closed by tsantalis** 2024-01-26 16:57 UTC
