### ISSUE TITLE
Timeout Exception opentripplanner/OpenTripPlanner 1c61d67

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#626] opened 2024-01-28 04:25 UTC
https://github.com/opentripplanner/OpenTripPlanner/commit/1c61d6751398254575ba759711803085a5990a6b timed out
```
91107220 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 1c61d6751398254575ba759711803085a5990a6b
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment] 2024-02-02 17:56
Duplicate of issue #622 #623

Refactorings at 1c61d6751398254575ba759711803085a5990a6b
Extract Variable	transmodelRequestContext : TransmodelRequestContext in method package getGraphQLExecutionResult(query String, router Router, variables Map<String,Object>, operationName String, timeout int, maxResolves int) : HashMap<String,Object> from class org.opentripplanner.ext.transmodelapi.TransmodelGraphIndex
Extract Variable	context : TransmodelRequestContext in method private createRequest(environment DataFetchingEnvironment) : RoutingRequest from class org.opentripplanner.ext.transmodelapi.TransmodelGraphQLPlanner
Add Parameter	routingService : RoutingService in method private getAgency(agencyId String, routingService RoutingService) : Agency from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private getAllRelevantAlerts(tripTimeShort TripTimeShort, routingService RoutingService) : Collection<AlertPatch> from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private getTripTimesForStop(stop Stop, startTimeSeconds Long, timeRage int, omitNonBoarding boolean, numberOfDepartures int, departuresPerLineAndDestinationDisplay Integer, authorityIdsWhiteListed Set<String>, lineIdsWhiteListed Set<FeedScopedId>, routingService RoutingService) : Stream<TripTimeShort> from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private destinationDisplayPerLine(t TripTimeShort, routingService RoutingService) : String from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private whiteListAuthoritiesAndOrLines(stream Stream<TripTimeShort>, authorityIds Set<String>, lineIds Set<FeedScopedId>, routingService RoutingService) : Stream<TripTimeShort> from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private isTripTimeShortAcceptable(tts TripTimeShort, authorityIds Set<String>, lineIds Set<FeedScopedId>, routingService RoutingService) : boolean from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method private isStopPlaceInUse(station StopCollection, routingService RoutingService) : boolean from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Add Parameter	routingService : RoutingService in method public getTripTimeShortForFromPlace(leg Leg, routingService RoutingService) : TripTimeShort from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Add Parameter	routingService : RoutingService in method public getTripTimeShortForToPlace(leg Leg, routingService RoutingService) : TripTimeShort from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Add Parameter	routingService : RoutingService in method public getAllTripTimeShortsForLegsTrip(leg Leg, routingService RoutingService) : List<TripTimeShort> from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Add Parameter	routingService : RoutingService in method public getIntermediateTripTimeShortsForLeg(leg Leg, routingService RoutingService) : List<TripTimeShort> from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Add Parameter	routingService : RoutingService in method private matchesQuayOrSiblingQuay(quayId FeedScopedId, candidate FeedScopedId, routingService RoutingService) : boolean from class org.opentripplanner.ext.transmodelapi.model.TripTimeShortHelper
Extract And Move Method	public route(request RoutingRequest, router Router) : RoutingResponse extracted from public plan(environment DataFetchingEnvironment) : PlanResponse in class org.opentripplanner.ext.transmodelapi.TransmodelGraphQLPlanner & moved to class org.opentripplanner.routing.RoutingService

**Closed by tsantalis** 2024-02-02 17:56 UTC
