### ISSUE TITLE
Timeout Exception opentripplanner/OpenTripPlanner 18f9bf5

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#629] opened 2024-01-28 04:25 UTC
https://github.com/opentripplanner/OpenTripPlanner/commit/18f9bf5a14ba6997e30a10528349ed32d54804e6 timed out
```
100616530 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 18f9bf5a14ba6997e30a10528349ed32d54804e6
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment] 2024-02-02 17:59
Duplicate of issues #622 #623

Refactorings at 18f9bf5a14ba6997e30a10528349ed32d54804e6
Nothing found

**Closed by tsantalis** 2024-02-02 17:59 UTC
