### ISSUE TITLE
NPE TGX-Android/Telegram-X 9165e87f02

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#577] opened 2024-01-25 21:00 UTC
NPE thrown while analyzing https://github.com/TGX-Android/Telegram-X/commit/ecc6d58dc62536cf93341d518bb620921cde384b
```
83289992 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 9165e87f02028947ca3aec8d22ad435cd85e1014
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "statementWithoutAnonymous1" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "statementWithoutAnonymous1" is null
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymous(UMLOperationBodyMapper.java:10856)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processAnonymousAndLambdas(UMLOperationBodyMapper.java:10686)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:8583)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:4802)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:451)
	at gr.uom.java.xmi.diff.UMLClassDiff.createBodyMappers(UMLClassDiff.java:188)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:110)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:164)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:162)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.lambda$detect$3(GitHistoryRefactoringMinerImpl.java:760)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tsantalis** [comment] 2024-01-26 12:58
@victorgveloso 
Duplicate of #575
Fixed in https://github.com/tsantalis/RefactoringMiner/commit/787c9a1e0422f399be43581469a6a7f05567da53

Refactorings at 9165e87f02028947ca3aec8d22ad435cd85e1014
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.BaseActivity
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.BaseActivity
Remove Method Modifier	final in method public onEmojiPartLoaded() : void from class org.thunderdog.challegram.BaseActivity
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.component.base.SettingView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.component.base.SettingView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.component.chat.MessagePreviewView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.component.chat.MessagePreviewView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.component.popups.JoinRequestsComponent
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.component.popups.JoinRequestsComponent
Remove Method Annotation	@Nullable in method public isSingleEmoji(str String) : boolean from class org.thunderdog.challegram.emoji.Emoji
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.emoji.EmojiUpdater
Change Attribute Type	targetView : EditText to targetView : TextView in class org.thunderdog.challegram.emoji.EmojiUpdater
Remove Parameter	editable : Editable in method private checkSpans(editable Editable) : void from class org.thunderdog.challegram.emoji.EmojiUpdater
Change Method Access Modifier	private to public in method public checkSpans() : void from class org.thunderdog.challegram.emoji.EmojiUpdater
Change Parameter Type	targetView : EditText to targetView : TextView in method public invalidateEmojiSpans(targetView TextView, force boolean) : void from class org.thunderdog.challegram.emoji.EmojiUpdater
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.emoji.EmojiUpdater
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.mediaview.MediaViewController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.mediaview.MediaViewController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.navigation.ComplexHeaderView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.ComplexHeaderView
Change Attribute Type	titleView : TextView to titleView : EmojiTextView in class org.thunderdog.challegram.navigation.DoubleHeaderView
Add Attribute Modifier	final in attribute private titleView : EmojiTextView from class org.thunderdog.challegram.navigation.DoubleHeaderView
Change Attribute Type	subtitleView : TextView to subtitleView : EmojiTextView in class org.thunderdog.challegram.navigation.DoubleHeaderView
Add Attribute Modifier	final in attribute private subtitleView : EmojiTextView from class org.thunderdog.challegram.navigation.DoubleHeaderView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.navigation.DrawerHeaderView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.DrawerHeaderView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.navigation.DrawerItemView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.DrawerItemView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.navigation.HeaderFilling
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.HeaderFilling
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.navigation.HeaderView
Change Variable Type	text : TextView to text : EmojiTextView in method public genTextTitle(context Context) : TextView from class org.thunderdog.challegram.navigation.HeaderView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.HeaderView
Change Variable Type	text : TextView to text : EmojiTextView in method public genOptionView(context Context, id int, string CharSequence, color int, icon int, onClickListener OnClickListener, themeProvider ThemeListenerList, forcedTheme ThemeDelegate) : TextView from class org.thunderdog.challegram.navigation.OptionsLayout
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.navigation.TelegramViewController.generateChatSearchView.new SettingsAdapter
Change Attribute Type	emojiListeners : List<Reference<EmojiLoadListener>> to emojiListeners : ReferenceList<EmojiLoadListener> in class org.thunderdog.challegram.telegram.TGLegacyManager
Change Variable Type	result : String to result : CharSequence in method private updateEmoji() : void from class org.thunderdog.challegram.ui.CallController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.ChatLinksController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.ChatLinksController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.ChatsController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.ChatsController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.EncryptionKeyController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.EncryptionKeyController
Change Variable Type	text : TextView to text : EmojiTextView in method public create(context Context, tdlib Tdlib, viewType int, onClickListener View.OnClickListener) : OptionHolder from class org.thunderdog.challegram.ui.MessageOptionsController.OptionHolder
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.MessagesController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.MessagesController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.PlaybackController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.PlaybackController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.SettingsAdapter
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.SettingsAdapter
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.SettingsCacheController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.SettingsCacheController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.SettingsThemeController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.SettingsThemeController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.widget.CustomTextView
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.widget.CustomTextView
Remove Attribute Modifier	final in attribute private emojiUpdater : EmojiUpdater from class org.thunderdog.challegram.widget.EmojiEditText
Extract Method	private init() : void extracted from public EmojiEditText(context Context) in class org.thunderdog.challegram.widget.EmojiEditText
Extract Method	private init() : void extracted from public EmojiEditText(context Context, attrs AttributeSet) in class org.thunderdog.challegram.widget.EmojiEditText
Extract Method	private init() : void extracted from public EmojiEditText(context Context, attrs AttributeSet, defStyleAttr int) in class org.thunderdog.challegram.widget.EmojiEditText
Add Parameter Annotation	@NonNull in parameter filters : InputFilter[] in method public setFilters(filters InputFilter[]) : void from class org.thunderdog.challegram.widget.EmojiEditText
Add Method Modifier	final in method public setFilters(filters InputFilter[]) : void from class org.thunderdog.challegram.widget.EmojiEditText
Add Class Annotation	@Deprecated in class org.thunderdog.challegram.widget.NoScrollTextView
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.component.chat.InlineResultsWrap
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.component.chat.InlineResultsWrap
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.telegram.TGLegacyManager.EmojiLoadListener
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.telegram.TGLegacyManager.EmojiLoadListener
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.EmojiListController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.EmojiListController
Rename Method	public onEmojiPartLoaded() : void renamed to public onEmojiUpdated(isPackSwitch boolean) : void in class org.thunderdog.challegram.ui.InstantViewController
Add Parameter	isPackSwitch : boolean in method public onEmojiUpdated(isPackSwitch boolean) : void from class org.thunderdog.challegram.ui.InstantViewController

**Closed by tsantalis** 2024-01-26 12:58 UTC
