### ISSUE TITLE
Timeout Exception opentripplanner/OpenTripPlanner 5fe875a

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#625] opened 2024-01-28 04:25 UTC
https://github.com/opentripplanner/OpenTripPlanner/commit/5fe875acf0e63d9762348d9b60c771ecb73a004c timed out
```
89667385 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 5fe875acf0e63d9762348d9b60c771ecb73a004c
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment] 2024-02-02 17:54
Duplicate of #622 #623

Refactorings at 5fe875acf0e63d9762348d9b60c771ecb73a004c
Move And Rename Method	package ReverseSearchTransitCalculator(s SearchParams, t RaptorTuningParameters) from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to package ReverseTransitCalculator(s SearchParams, t RaptorTuningParameters) from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public plusDuration(time int, duration int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public plusDuration(time int, duration int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public minusDuration(time int, duration int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public minusDuration(time int, duration int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public duration(timeA int, timeB int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public duration(timeA int, timeB int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public stopArrivalTime(onTrip T, stopPositionInPattern int, alightSlack int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public stopArrivalTime(onTrip T, stopPositionInPattern int, alightSlack int) : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public exceedsTimeLimit(time int) : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public exceedsTimeLimit(time int) : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public exceedsTimeLimitReason() : String from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public exceedsTimeLimitReason() : String from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public isBest(subject int, candidate int) : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public isBest(subject int, candidate int) : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public unreachedTime() : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public unreachedTime() : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public rangeRaptorMinutes() : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public rangeRaptorMinutes() : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public oneIterationOnly() : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public oneIterationOnly() : boolean from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public patternStopIterator(nStopsInPattern int) : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public patternStopIterator(nStopsInPattern int) : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public patternStopIterator(onTripStopPos int, nStopsInPattern int) : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public patternStopIterator(onTripStopPos int, nStopsInPattern int) : IntIterator from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public createTripSearch(timeTable RaptorTimeTable<T>) : TripScheduleSearch<T> from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public createTripSearch(timeTable RaptorTimeTable<T>) : TripScheduleSearch<T> from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Method	public createExactTripSearch(timeTable RaptorTimeTable<T>) : TripScheduleSearch<T> from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to public createExactTripSearch(timeTable RaptorTimeTable<T>) : TripScheduleSearch<T> from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private tripSearchBinarySearchThreshold : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to private tripSearchBinarySearchThreshold : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private latestArrivalTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to private latestArrivalTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private searchWindowInSeconds : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to private searchWindowInSeconds : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private earliestAcceptableDepartureTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to private earliestAcceptableDepartureTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private iterationStep : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator to private iterationStep : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private latestArrivalTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculatorTest to private latestArrivalTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Add Attribute Modifier	final in attribute private latestArrivalTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private earliestAcceptableDepartureTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculatorTest to private earliestAcceptableDepartureTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Add Attribute Modifier	final in attribute private earliestAcceptableDepartureTime : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Attribute	private iterationStep : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculatorTest to private iterationStep : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Add Attribute Modifier	final in attribute private iterationStep : int from class org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Move Class	org.opentripplanner.transit.raptor.api.TestLeg moved to org.opentripplanner.transit.raptor._shared.TestLeg
Move Class	org.opentripplanner.transit.raptor.api.TestRoute moved to org.opentripplanner.transit.raptor._shared.TestRoute
Move Class	org.opentripplanner.transit.raptor.api.TestRaptorTripSchedule moved to org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule
Rename Class	org.opentripplanner.transit.raptor.rangeraptor.transit.ForwardSearchTransitCalculator renamed to org.opentripplanner.transit.raptor.rangeraptor.transit.ForwardTransitCalculator
Rename Class	org.opentripplanner.transit.raptor.rangeraptor.transit.ForwardSearchTransitCalculatorTest renamed to org.opentripplanner.transit.raptor.rangeraptor.transit.ForwardTransitCalculatorTest
Rename Class	org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculatorTest renamed to org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculatorTest
Merge Class	[org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculator, org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseSearchTransitCalculatorTest] merged to org.opentripplanner.transit.raptor.rangeraptor.transit.ReverseTransitCalculator
Add Parameter	defaultRoutingRequest : RoutingRequest in method package TransmodelGraphIndex(graph Graph, defaultRoutingRequest RoutingRequest) from class org.opentripplanner.ext.transmodelapi.TransmodelGraphIndex
Rename Method	public addSecondsPastMidnight(name String, timeSecondsPastMidnight int, defaultValue int) : ToStringBuilder renamed to public addServiceTime(name String, timeSecondsPastMidnight int, defaultValue int) : ToStringBuilder in class org.opentripplanner.model.base.ToStringBuilder
Rename Method	public addSecondsPastMidnight(secondsPastMidnight int) : ValueObjectToStringBuilder renamed to public addServiceTime(secondsPastMidnight int) : ValueObjectToStringBuilder in class org.opentripplanner.model.base.ValueObjectToStringBuilder
Rename Method	public addSecondsPastMidnight(secondsPastMidnight int, notSet int) : ValueObjectToStringBuilder renamed to public addServiceTime(secondsPastMidnight int, notSet int) : ValueObjectToStringBuilder in class org.opentripplanner.model.base.ValueObjectToStringBuilder
Rename Attribute	first : boolean to skipSep : boolean in class org.opentripplanner.model.base.ValueObjectToStringBuilder
Reorder Parameter	[fromTime : int, toStop : int, toTime : int, next : TransitPathLeg<T>] to [toStop : int, fromTime : int, toTime : int, next : TransitPathLeg<T>] in method public AccessPathLeg(toStop int, fromTime int, toTime int, next TransitPathLeg<T>) from class org.opentripplanner.transit.raptor.api.path.AccessPathLeg
Rename Method	public totalTravelDurationInSeconds() : int renamed to public travelDurationInSeconds() : int in class org.opentripplanner.transit.raptor.api.path.Path
Add Attribute Modifier	final in attribute private egressPathLeg : EgressPathLeg<T> from class org.opentripplanner.transit.raptor.api.path.Path
Extract Method	private findEgressLeg(leg PathLeg<S>) : EgressPathLeg<S> extracted from public egressLeg() : EgressPathLeg<T> in class org.opentripplanner.transit.raptor.api.path.Path
Parameterize Variable	leg : PathLeg<T> to leg : PathLeg<S> in method private findEgressLeg(leg PathLeg<S>) : EgressPathLeg<S> from class org.opentripplanner.transit.raptor.api.path.Path
Change Variable Type	leg : PathLeg<T> to leg : PathLeg<S> in method private findEgressLeg(leg PathLeg<S>) : EgressPathLeg<S> from class org.opentripplanner.transit.raptor.api.path.Path
Remove Parameter	endTime : int in method public Path(accessLeg AccessPathLeg<T>, endTime int, numberOfTransfers int, cost int) from class org.opentripplanner.transit.raptor.api.path.Path
Remove Parameter	numberOfTransfers : int in method public Path(accessLeg AccessPathLeg<T>, endTime int, numberOfTransfers int, cost int) from class org.opentripplanner.transit.raptor.api.path.Path
Add Parameter	transferSlack : int in method public defaults(transferSlack int, boardSlack int, alightSlack int) : RaptorSlackProvider from class org.opentripplanner.transit.raptor.api.transit.RaptorSlackProvider
Add Parameter	boardSlack : int in method public defaults(transferSlack int, boardSlack int, alightSlack int) : RaptorSlackProvider from class org.opentripplanner.transit.raptor.api.transit.RaptorSlackProvider
Add Parameter	alightSlack : int in method public defaults(transferSlack int, boardSlack int, alightSlack int) : RaptorSlackProvider from class org.opentripplanner.transit.raptor.api.transit.RaptorSlackProvider
Rename Variable	duration : int to totalTravelTime : int in method package transitToStop(previousStopArrival AbstractStopArrival<T>, stop int, alightTime int, alightSlack int, boardTime int, trip T) : void from class org.opentripplanner.transit.raptor.rangeraptor.multicriteria.McRangeRaptorWorkerState
Add Parameter	pathMapper : PathMapper<T> in method public DestinationArrivalPaths(paretoComparator ParetoComparator<Path<T>>, calculator TransitCalculator, pathMapper PathMapper<T>, debugHandlerFactory DebugHandlerFactory<T>, lifeCycle WorkerLifeCycle) from class org.opentripplanner.transit.raptor.rangeraptor.path.DestinationArrivalPaths
Rename Parameter	transitLeg : TransitPathLeg<T> to nextLeg : TransitPathLeg<T> in method private createAccessPathLeg(from ArrivalView<T>, nextLeg TransitPathLeg<T>) : AccessPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapper
Change Parameter Type	calculator : TransitCalculator to slackProvider : RaptorSlackProvider in method public ForwardPathMapper(slackProvider RaptorSlackProvider) from class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapper
Rename Parameter	calculator : TransitCalculator to slackProvider : RaptorSlackProvider in method public ForwardPathMapper(slackProvider RaptorSlackProvider) from class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapper
Rename Attribute	calculator : TransitCalculator to transitLayerSlackProvider : RaptorSlackProvider in class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapper
Change Attribute Type	calculator : TransitCalculator to transitLayerSlackProvider : RaptorSlackProvider in class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapper
Rename Method	private mapToPathLeg(to ArrivalView<T>, transitBoardTime int) : PathLeg<T> renamed to private mapNextLeg(fromStopArrival ArrivalView<T>, tripSchedule T, prevStopArrivalTime int) : PathLeg<T> in class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Extract Method	package mapAccessLeg(destinationArrival DestinationArrival<T>, lastStopArrival ArrivalView<T>) : AccessPathLeg<T> extracted from public mapToPath(to DestinationArrival<T>) : Path<T> in class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Merge Variable	[destinationArrivalTime : int, numberOfTransfers : int] to destinationArrival : DestinationArrival<T> in method package mapAccessLeg(destinationArrival DestinationArrival<T>, lastStopArrival ArrivalView<T>) : AccessPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Variable	from : ArrivalView<T> to lastStopArrival : ArrivalView<T> in method public mapToPath(destinationArrival DestinationArrival<T>) : Path<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	to : DestinationArrival<T> to destinationArrival : DestinationArrival<T> in method public mapToPath(destinationArrival DestinationArrival<T>) : Path<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Variable	from : ArrivalView<T> to toStopArrival : ArrivalView<T> in method private mapToTransit(fromStopArrival ArrivalView<T>) : TransitPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	to : ArrivalView<T> to fromStopArrival : ArrivalView<T> in method private mapToTransit(fromStopArrival ArrivalView<T>) : TransitPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Variable	trip : T to tripSchedule : T in method private mapToTransit(fromStopArrival ArrivalView<T>) : TransitPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Variable	from : ArrivalView<T> to toStopArrival : ArrivalView<T> in method private mapToTransfer(fromStopArrival ArrivalView<T>) : TransferPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	to : ArrivalView<T> to fromStopArrival : ArrivalView<T> in method private mapToTransfer(fromStopArrival ArrivalView<T>) : TransferPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Change Parameter Type	calculator : TransitCalculator to slackProvider : RaptorSlackProvider in method public ReversePathMapper(slackProvider RaptorSlackProvider) from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	calculator : TransitCalculator to slackProvider : RaptorSlackProvider in method public ReversePathMapper(slackProvider RaptorSlackProvider) from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	to : ArrivalView<T> to fromStopArrival : ArrivalView<T> in method private mapNextLeg(fromStopArrival ArrivalView<T>, tripSchedule T, prevStopArrivalTime int) : PathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	transitBoardTime : int to prevStopArrivalTime : int in method private mapNextLeg(fromStopArrival ArrivalView<T>, tripSchedule T, prevStopArrivalTime int) : PathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Add Parameter	tripSchedule : T in method private mapNextLeg(fromStopArrival ArrivalView<T>, tripSchedule T, prevStopArrivalTime int) : PathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Attribute	calculator : TransitCalculator to transitLayerSlackProvider : RaptorSlackProvider in class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Change Attribute Type	calculator : TransitCalculator to transitLayerSlackProvider : RaptorSlackProvider in class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Add Parameter	boardSlackProvider : ToIntFunction<RaptorTripPattern> in method public StopsCursor(stops Stops<T>, transitCalculator TransitCalculator, boardSlackProvider ToIntFunction<RaptorTripPattern>) from class org.opentripplanner.transit.raptor.rangeraptor.standard.stoparrivals.view.StopsCursor
Rename Parameter	transitDepartureTime : int to transitLeg : StopArrivalViewAdapter.Transit<T> in method package access(stop int, transitLeg StopArrivalViewAdapter.Transit<T>) : ArrivalView<T> from class org.opentripplanner.transit.raptor.rangeraptor.standard.stoparrivals.view.StopsCursor
Change Parameter Type	transitDepartureTime : int to transitLeg : StopArrivalViewAdapter.Transit<T> in method package access(stop int, transitLeg StopArrivalViewAdapter.Transit<T>) : ArrivalView<T> from class org.opentripplanner.transit.raptor.rangeraptor.standard.stoparrivals.view.StopsCursor
Add Parameter	boardSlack : int in method private newAccessView(stop int, transitDepartureTime int, boardSlack int) : ArrivalView<T> from class org.opentripplanner.transit.raptor.rangeraptor.standard.stoparrivals.view.StopsCursor
Rename Attribute	slackProvider : SlackProvider to pathMapper : PathMapper<T> in class org.opentripplanner.transit.raptor.rangeraptor.transit.SearchContext
Change Attribute Type	slackProvider : SlackProvider to pathMapper : PathMapper<T> in class org.opentripplanner.transit.raptor.rangeraptor.transit.SearchContext
Encapsulate Attribute	private pathMapper : PathMapper<T> from class org.opentripplanner.transit.raptor.rangeraptor.transit.SearchContext
Change Attribute Access Modifier	public to private in attribute private BOARD_SLACK : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1000 : int to A_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public A_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public A_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1035 : int to T1_END : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public T1_END : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1100 : int to T2_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public T2_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1123 : int to T2_END : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public T2_END : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1140 : int to T3_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public T3_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1153 : int to E_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public E_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1200 : int to E_END : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public E_END : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Variable	arrival : AbstractStopArrival to prevArrival : AbstractStopArrival in method public basicTripByForwardSearch() : Egress from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Variable Type	leg5 : PathLeg<TestRaptorTripSchedule> to leg5 : TransitPathLeg<TestRaptorTripSchedule> in method public basicTripAsPath() : Path<TestRaptorTripSchedule> from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Variable Type	leg4 : PathLeg<TestRaptorTripSchedule> to leg4 : TransitPathLeg<TestRaptorTripSchedule> in method public basicTripAsPath() : Path<TestRaptorTripSchedule> from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Variable Type	leg2 : PathLeg<TestRaptorTripSchedule> to leg2 : TransitPathLeg<TestRaptorTripSchedule> in method public basicTripAsPath() : Path<TestRaptorTripSchedule> from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1035 : int to W1_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public W1_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1038 : int to W1_END : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public W1_END : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T1000 : int to T1_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public T1_START : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T0958 : int to A_END : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Change Attribute Access Modifier	private to public in attribute public A_END : int from class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Rename Attribute	T0953 : int to A_START : int in class org.opentripplanner.transit.raptor._shared.StopArrivalsTestData
Add Attribute Modifier	final in attribute private subject : Path<TestRaptorTripSchedule> from class org.opentripplanner.transit.raptor.api.path.PathTest
Extract Variable	leg : PathLeg<?> in method public mapToPathForwardSearch() : void from class org.opentripplanner.transit.raptor.rangeraptor.path.ForwardPathMapperTest
Extract Variable	leg : PathLeg<?> in method public mapToPathReverseSearch() : void from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapperTest
Change Parameter Type	arrivalTimes : int... to arrivalTimes : int[] in method private TestRaptorTripSchedule(name String, arrivalTimes int[], depatureTimes int[], stopIndexes int[]) from class org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule
Split Parameter	departureDelay : int to [name : String, depatureTimes : int[], stopIndexes : int[]] in method private TestRaptorTripSchedule(name String, arrivalTimes int[], depatureTimes int[], stopIndexes int[]) from class org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule
Split Attribute	departureDelay : int to [name : String, stopIndexes : int[], depatureTimes : int[]] in class org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule
Remove Parameter	boardSlackInSeconds : int in method package ForwardSearchTransitCalculator(tripSearchBinarySearchThreshold int, boardSlackInSeconds int, earliestDepartureTime int, searchWindowInSeconds int, latestAcceptableArrivalTime int, iterationStep int) from class org.opentripplanner.transit.raptor.rangeraptor.transit.ForwardSearchTransitCalculator
Move Method	private createEnum(name String, values T[], mapping Function<T,String>) : GraphQLEnumType from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema to private createEnum(name String, values T[], mapping Function<T,String>) : GraphQLEnumType from class org.opentripplanner.ext.transmodelapi.model.EnumTypes
Extract Class	org.opentripplanner.ext.transmodelapi.model.EnumTypes from class org.opentripplanner.ext.transmodelapi.TransmodelIndexGraphQLSchema
Move Attribute	private departureDelay : int from class org.opentripplanner.transit.raptor.api.TestRaptorTripSchedule to private departureDelay : int from class org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule.Builder
Remove Attribute Modifier	final in attribute private departureDelay : int from class org.opentripplanner.transit.raptor.api.TestRaptorTripSchedule
Extract Class	org.opentripplanner.transit.raptor._shared.TestRaptorTripSchedule.Builder from class org.opentripplanner.transit.raptor.api.TestRaptorTripSchedule
Add Method Modifier	static in method public mapRoutingRequest(c NodeAdapter) : RoutingRequest from class org.opentripplanner.standalone.config.RoutingRequestMapper
Move And Rename Method	public routingRequestDefaults(c NodeAdapter) : RoutingRequest from class org.opentripplanner.standalone.config.RouterConfig to public mapRoutingRequest(c NodeAdapter) : RoutingRequest from class org.opentripplanner.standalone.config.RoutingRequestMapper
Rename Variable	egressArrivalTime : int to toTime : int in method private mapToEgressLeg(stopArrival ArrivalView<T>, tripSchedule T, transitAlightTime int) : EgressPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	to : ArrivalView<T> to stopArrival : ArrivalView<T> in method private mapToEgressLeg(stopArrival ArrivalView<T>, tripSchedule T, transitAlightTime int) : EgressPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Rename Parameter	transitBoardTime : int to transitAlightTime : int in method private mapToEgressLeg(stopArrival ArrivalView<T>, tripSchedule T, transitAlightTime int) : EgressPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Add Parameter	tripSchedule : T in method private mapToEgressLeg(stopArrival ArrivalView<T>, tripSchedule T, transitAlightTime int) : EgressPathLeg<T> from class org.opentripplanner.transit.raptor.rangeraptor.path.ReversePathMapper
Remove Parameter	boardSlackInSeconds : int in method public testDummyCalculator(boardSlackInSeconds int, forward boolean) : TransitCalculator from class org.opentripplanner.transit.raptor.rangeraptor.transit.TransitCalculator

**Closed by tsantalis** 2024-02-02 17:54 UTC
