### ISSUE TITLE
Statement mapping inaccuracy

### ISSUE THREAD

**Issue by pedramnoori** [tsantalis/RefactoringMiner#475] opened 2023-05-19 19:19 UTC
**Problem**

Statement mapping inaccuracy within an Extract Method + Missing Merge Conditional refactoring

**Commit**

https://github.com/adjust/android_sdk/commit/d1753466e2acd2d93844031d488e8f5d13b835ea

**Target refactorings**

**1-** Extract Method private **canInit()** : boolean extracted **from** private **initInternal()** : void in class com.adeven.adjustio.**ActivityHandler**

**2-**  Extract Method private **canTrackRevenueOrEvent**(revenueBuilder PackageBuilder) : boolean extracted **from** private **eventInternal**(eventBuilder PackageBuilder) : void in class com.adeven.adjustio.**ActivityHandler**

**3-** Extract Method private **canTrackRevenueOrEvent**(revenueBuilder PackageBuilder) : boolean extracted **from** private **revenueInternal**(revenueBuilder PackageBuilder) : void in class com.adeven.adjustio.**ActivityHandler**

**Description**

Within the aforementioned Extract Method refactorings, three (or four) if statements have been extracted and transformed to a return statement. The statement mapping reported by RefactoringMiner is not accurate enough to truly express this extraction. Currecntly, just one of the if statements in the parent version has been mapped with the whole return statement in the child version (extracted method). 

Note that this change can be also considered as a Merge Conditional refactoring.

**Comment by tsantalis** [comment] 2023-05-23 18:59
pending clarification from @pouryafard75 about the differences in the mappings of `canTrackRevenueOrEvent()` calls.

![Screenshot from 2023-05-23 13-53-12](https://github.com/tsantalis/RefactoringMiner/assets/1483516/cfdf8112-52e5-45c3-80ea-546ca08985bb)

**Comment by tsantalis** [comment] 2023-05-24 10:45
After @pouryafard75 fix discarding the mapping for SimpleNames when the parent is not matched.
Still the diff is not ideal, and this fix is quite risky.
We will implement sub-expression LeafMapping to support this refactoring.

![Screenshot from 2023-05-24 06-43-03](https://github.com/tsantalis/RefactoringMiner/assets/1483516/0391cb2d-b774-4a98-b481-a3f089c23ad3)

**Comment by tsantalis** [comment] 2023-05-26 10:29
Commit https://github.com/tsantalis/RefactoringMiner/commit/68319df7c453a52778d7853b59d5a2bfe5ec5065
implements sub-expression LeafMappings for `IntersectionReplacement`

**Comment by tsantalis** [comment] 2023-06-20 00:51
The issue is considered fixed in the core.

![Screenshot from 2023-06-19 20-49-54](https://github.com/tsantalis/RefactoringMiner/assets/1483516/35b42c9b-8ea7-4d5e-ab28-620b8d10d644)

**Comment by tsantalis** [comment] 2023-12-26 01:18
@pouryafard75 
I am re-opening this issue, because I think the improvement I made was not clear.

Each leafMapping within the two Extract Method mappers, has one `IntersectionReplacement` in the set of replacements.
The `IntersectionReplacement` implements `LeafMappingProvider` and can provide a list of sub-expression mappings.

I think we do not utilize this anywhere.

**Comment by tsantalis** [comment] 2023-12-26 16:37
@pouryafard75 
There is a 3-to-1 method invocation mapping:
L270: `checkEventTokenNotNull(eventBuilder.getEventToken())`
L273: `checkEventTokenLength(eventBuilder.getEventToken())`
L307: `checkEventTokenLength(revenueBuilder.getEventToken())`
matched with
R246: `checkEventToken(revenueBuilder.getEventToken())`

Note that methods
`checkEventTokenNotNull` and `checkEventTokenLength` are merged to method `checkEventToken`

All 3 mappings have the same AST structure: `methodName(method-invocation-argument)`, but only one of them is matched. This is a case of multi-mapping, where all of them should be accepted/applied.

![Screenshot from 2023-12-26 11-27-11](https://github.com/tsantalis/RefactoringMiner/assets/1483516/f908f574-1167-4668-949d-cf29287c0e26)

**Comment by tsantalis** [comment] 2023-12-26 20:55
![Screenshot from 2023-12-26 15-54-42](https://github.com/tsantalis/RefactoringMiner/assets/1483516/86e71e38-fe3b-470a-af0c-966cffdac514)

**Closed by tsantalis** 2023-12-26 20:55 UTC
