### ISSUE TITLE
Timeout Exception opentripplanner/OpenTripPlanner 61fb84c

### ISSUE THREAD

**Issue by victorgveloso** [tsantalis/RefactoringMiner#628] opened 2024-01-28 04:25 UTC
https://github.com/opentripplanner/OpenTripPlanner/commit/61fb84c0e2fd2362fd413d7a5bf3963223a52c50 timed out
```
94157091 [main] ERROR b.u.d.l.r.o.AnalyzeProjectsHandler - Error analyzing commit 61fb84c0e2fd2362fd413d7a5bf3963223a52c50
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:762)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:808)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.lambda$analyzeProject$0(AnalyzeAllCommits.java:61)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.extractProjectPath(TaskWithProjectLock.java:49)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.analyzeProject(AnalyzeAllCommits.java:52)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.doTask(AnalyzeAllCommits.java:45)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.TaskWithProjectLock.doTask(TaskWithProjectLock.java:75)
	at br.ufmg.dcc.labsoft.refactoringanalyzer.operations.AnalyzeAllCommits.main(AnalyzeAllCommits.java:27)
```

**Comment by tsantalis** [comment] 2024-02-02 17:58
Duplicate of issue #622 #623

Refactorings at 61fb84c0e2fd2362fd413d7a5bf3963223a52c50
Change Attribute Access Modifier	public to private in attribute private agenciesForFeedId : Map<String,Map<String,Agency>> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private agenciesForFeedId : Map<String,Map<String,Agency>> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private operatorForId : Map<FeedScopedId,Operator> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private operatorForId : Map<FeedScopedId,Operator> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private feedInfoForId : Map<String,FeedInfo> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private feedInfoForId : Map<String,FeedInfo> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private stopForId : Map<FeedScopedId,Stop> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private stopForId : Map<FeedScopedId,Stop> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private tripForId : Map<FeedScopedId,Trip> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private tripForId : Map<FeedScopedId,Trip> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private routeForId : Map<FeedScopedId,Route> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private routeForId : Map<FeedScopedId,Route> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private stopVertexForStop : Map<Stop,TransitStopVertex> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private stopVertexForStop : Map<Stop,TransitStopVertex> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private patternForTrip : Map<Trip,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private patternForTrip : Map<Trip,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private patternsForFeedId : Multimap<String,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private patternsForFeedId : Multimap<String,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private patternsForRoute : Multimap<Route,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private patternsForRoute : Multimap<Route,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private patternsForStop : Multimap<Stop,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private patternsForStop : Multimap<Stop,TripPattern> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private multiModalStationForStations : Map<Station,MultiModalStation> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private multiModalStationForStations : Map<Station,MultiModalStation> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	package to private in attribute private stopSpatialIndex : HashGridSpatialIndex<TransitStopVertex> from class org.opentripplanner.routing.graph.GraphIndex
Encapsulate Attribute	private stopSpatialIndex : HashGridSpatialIndex<TransitStopVertex> from class org.opentripplanner.routing.graph.GraphIndex
Change Attribute Access Modifier	public to private in attribute private serviceCodesRunningForDate : Map<ServiceDate,TIntSet> from class org.opentripplanner.routing.graph.GraphIndex

**Closed by tsantalis** 2024-02-02 17:58 UTC
