### ISSUE TITLE
NPE on detectAtCommit()

### ISSUE THREAD

**Issue by mo7aammd** [tsantalis/RefactoringMiner#780] opened 2024-09-18 13:22 UTC
https://github.com/apache/cassandra/commit/5726625a5c7cf47a67509540f7146d05b668bc20
---------------------------------------------------------------------------------------------------------
Error => java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "type" is null
---------------------------------------------------------------------------------------------------------
[main] WARN org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl - Ignored revision 5726625a5c7cf47a67509540f7146d05b668bc20 due to error
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "type" is null
	at gr.uom.java.xmi.LeafType.equalClassType(LeafType.java:99)
	at gr.uom.java.xmi.UMLType.matchWithParentClassTypeParameterChange(UMLType.java:358)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.equalType(VariableReplacementAnalysis.java:502)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.variableAppearsInExtractedMethod(VariableReplacementAnalysis.java:2754)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.consistencyCheck(VariableReplacementAnalysis.java:2328)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.replacementInLocalVariableDeclaration(VariableReplacementAnalysis.java:2324)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.findConsistentVariableRenames(VariableReplacementAnalysis.java:1713)
	at gr.uom.java.xmi.decomposition.VariableReplacementAnalysis.<init>(VariableReplacementAnalysis.java:160)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.computeRefactoringsWithinBody(UMLOperationBodyMapper.java:3084)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.getRefactorings(UMLOperationBodyMapper.java:3034)
	at gr.uom.java.xmi.diff.UMLAbstractClassDiff.processMapperRefactorings(UMLAbstractClassDiff.java:943)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForExtractedOperations(UMLClassBaseDiff.java:2888)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:168)
	at gr.uom.java.xmi.diff.UMLModelDiff.checkForRenamedClasses(UMLModelDiff.java:849)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:169)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:163)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAtCommit(GitHistoryRefactoringMinerImpl.java:801)

**Comment by tsantalis** [comment] 2024-09-18 16:17
@mo7aammd 
The issue is fixed. It will be in the next release, which is not so urgent. I think this is a rare exception.

**Closed by tsantalis** 2024-09-18 16:17 UTC
